apiVersion: v1
kind: Service
metadata:
  name: nuttoo-api
  namespace: nuttoo
  labels:
    app.kubernetes.io/name: nuttoo-api
    app.kubernetes.io/part-of: nuttoo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nuttoo-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
